# Generated by Django 3.2.2 on 2021-05-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrace',
            name='time_limti',
            field=models.DateTimeField(blank=True),
        ),
    ]
